### ISSUE TITLE
int64_t serializing issue

### ISSUE THREAD

**Issue by Mishanok** [Winderton/xplatform#1]
<h2><b>Hi!</b></h2>
</br>
<h4>At line 213 int64_t is packing as int32_t variable, what is possibly lose some data</h4>
</br>
Could you please give me an access to this repo so I could create Pull Requests?
</br>
<b><h3>Thank you very much!</h3></b>

**Comment by Winderton** [comment]
The repo should be open for pull requests. And thanks, i've just worked that out.
