### ISSUE TITLE
Как запустить? 

### ISSUE THREAD

**Issue by verbitsky-vladislav** [Winderton/xplatform#8]
Очень мало информации по тому как это запустить...
Я простой JavaScriptер, посмотрел твои ролики и пошел запускать всякое на гите, изучать чужие проекты и т.д., но столкнулся с тем что вообще без понятия как можно запустить какие-то модули тут. Можешь в readme добавить как это делается?

**Comment by Winderton** [comment]
Появится в каждом модуле, плюс общий ридми, да.
